### ISSUE TITLE
Name of this tool

### ISSUE THREAD

**Issue by loup-brun** [corsaire-chaparral/registre-coch#1]
Find a proper name for this tool.

URL in mind?

**Comment by loup-brun** [comment]
ideas:

- coch.app
  - je.coch.app
  - db.coch.app (CouchDB, eh)
- coch-check.app
- cochcheck.app
- coch-check.ca
-  co-verif.ca

**Comment by obenn** [comment]
Maybe registre.app?

**Comment by loup-brun** [comment]
presences.corsaire-chaparral.org for first deploys

**Comment by loup-brun** [comment]
For now:

- COCH.APP for the general info site
- JE.COCH.APP for the client app
- DB.COCH.APP for the CouchDB backend
