### ISSUE TITLE
Event editing history?

### ISSUE THREAD

**Issue by loup-brun** [corsaire-chaparral/registre-coch#4]
Keep track of edits to an event _after it happened_?

Example use case: after an event happens, the manager may have forgotten to check a member present; or entered a wrong one.

But this raises a potential issue: data integrity.

Keeping track of changes history could improve the quality of the source of truth.

A time frame could be set (e.g. Changes can be made within 24 hours after the event was created to avoid subsequent commits.)

**Comment by obenn** [comment]
I like that last suggestion. You'd want things to be flexible as the event happens, but set in stone once done.

**Comment by loup-brun** [comment]
Document revisions are baked-in to CouchDB’s .

Limiting revisions could be implemented in the future, but it is not mandatory at this stage.
